server:
  port: 8501
spring:
  application:
    name: spring-cloud-consul-producer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: service-producer
  datasource:
    url: jdbc:mysql://localhost:3306/tale?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mapper/*.xml


